// tailwind-config.js
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c2def0",
        primary: "#5f5e5e",
        "tertiary-container": "#d0ecff",
        background: "#f9f9f9",
        tertiary: "#486272",
        "on-error": "#fff7f6",
        "secondary-dim": "#535353",
        "surface-bright": "#f9f9f9",
        "secondary-fixed": "#e4e2e2",
        "surface-variant": "#dde4e5",
        "error-dim": "#4e0309",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#486272",
        "secondary-container": "#e4e2e2",
        "on-tertiary-container": "#3e5868",
        "on-primary-fixed-variant": "#5c5b5b",
        "tertiary-fixed": "#d0ecff",
        "on-primary-fixed": "#403f3f",
        "primary-container": "#e5e2e1",
        "outline-variant": "#adb3b4",
        "secondary-fixed-dim": "#d5d4d4",
        "surface-container-high": "#e4e9ea",
        "surface-dim": "#d4dbdd",
        "tertiary-dim": "#3c5666",
        "on-secondary-fixed-variant": "#5b5b5b",
        "on-surface": "#2d3435",
        "inverse-surface": "#0c0f0f",
        "on-primary": "#faf7f6",
        error: "#9f403d",
        "primary-dim": "#535252",
        "surface-container-low": "#f2f4f4",
        "on-primary-container": "#525151",
        "error-container": "#fe8983",
        secondary: "#5f5f5f",
        surface: "#f9f9f9",
        "on-error-container": "#752121",
        "on-tertiary-fixed": "#2c4655",
        "inverse-primary": "#ffffff",
        outline: "#757c7d",
        "surface-container-highest": "#dde4e5",
        "on-surface-variant": "#5a6061",
        "on-secondary-fixed": "#3f3f3f",
        "on-secondary-container": "#515252",
        "primary-fixed-dim": "#d6d4d3",
        "surface-tint": "#5f5e5e",
        "on-tertiary": "#f4faff",
        "inverse-on-surface": "#9c9d9d",
        "surface-container": "#ebeeef",
        "primary-fixed": "#e5e2e1",
        "on-secondary": "#faf8f8",
        "on-background": "#2d3435",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
};
